apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-eks
  region: ap-south-1
  version: "1.36"

managedNodeGroups:
  - name: learning-node
    instanceType: t3a.small

    desiredCapacity: 1
    minSize: 1
    maxSize: 3

    volumeSize: 20
    volumeType: gp3

    amiFamily: Ubuntu2404

    privateNetworking: false

vpc:
  nat:
    gateway: Disable
