apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: my-tnttfc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: efs-pv
