apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-pvc
  namespace: my-tnttfc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 5Gi
