# Generated by Django 4.2.23 on 2025-09-29 06:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tech_repo', '0002_alter_district_name_alter_district_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to='director_aadhaars/')),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(max_length=254)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('aadhaar', models.FileField(blank=True, null=True, upload_to='inventor_aadhaars/')),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(max_length=254)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
