# Generated by Django 4.2.23 on 2025-08-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademarkapplication',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
