# Generated by Django 4.2.23 on 2025-09-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0002_alter_trademarkapplication_date_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorartsearch',
            name='inventor_details',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
