# Generated by Django 4.2.9 on 2025-09-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0003_priorartsearch_inventor_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarkapplication',
            name='inventor_details',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
