# Generated by Django 5.2.5 on 2025-09-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_repo', '0002_alter_district_name_alter_district_state_and_more'),
        ('techforms', '0004_trademarkapplication_inventor_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademarkapplication',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.district'),
        ),
        migrations.AlterField(
            model_name='trademarkapplication',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.state'),
        ),
    ]
