# Generated by Django 5.2.5 on 2025-09-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0005_alter_trademarkapplication_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarkapplication',
            name='class_details',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trademarkapplication',
            name='trademark_image',
            field=models.FileField(default=1, upload_to='trademark_images/'),
            preserve_default=False,
        ),
    ]
