# Generated by Django 5.2.5 on 2025-09-04 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0006_trademarkapplication_class_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademarkapplication',
            name='contact_number',
            field=models.CharField(help_text='Must be exactly 10 digits.', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='trademarkapplication',
            name='inventor_details',
            field=models.TextField(blank=True, default='{}', help_text='JSON string storing inventor details: {inventor_1: {name, designation, dob, qualification, mobile, email}, ...}'),
        ),
    ]
