# Generated by Django 4.2.23 on 2025-09-05 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0007_alter_trademarkapplication_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRLAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('organisation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(help_text='Must be exactly 10 digits.', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('technology_title', models.CharField(max_length=255)),
                ('field_of_invention', models.CharField(max_length=255)),
                ('technology_description', models.TextField(max_length=5000)),
                ('market_segment', models.CharField(max_length=255)),
                ('patent_details', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
