# Generated by Django 4.2.23 on 2025-09-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0008_trlassessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trlassessment',
            old_name='applicant_name',
            new_name='inventor_name',
        ),
    ]
