# Generated by Django 4.2.23 on 2025-09-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0009_rename_applicant_name_trlassessment_inventor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='inventor_details',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
