# Generated by Django 4.2.23 on 2025-09-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_repo', '0002_alter_district_name_alter_district_state_and_more'),
        ('techforms', '0010_innovationvoucherapplication_inventor_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovationvoucherapplication',
            old_name='applicant_name',
            new_name='startup_name',
        ),
        migrations.AlterField(
            model_name='innovationvoucherapplication',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.district'),
        ),
        migrations.AlterField(
            model_name='innovationvoucherapplication',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.state'),
        ),
    ]
