# Generated by Django 4.2.23 on 2025-09-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0011_rename_applicant_name_innovationvoucherapplication_startup_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovationvoucherapplication',
            old_name='inventor_count',
            new_name='director_count',
        ),
        migrations.RenameField(
            model_name='innovationvoucherapplication',
            old_name='inventor_details',
            new_name='director_details',
        ),
    ]
