# Generated by Django 4.2.23 on 2025-09-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_repo', '0002_alter_district_name_alter_district_state_and_more'),
        ('techforms', '0012_rename_inventor_count_innovationvoucherapplication_director_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patentapplication',
            name='applicant_name',
        ),
        migrations.AddField(
            model_name='patentapplication',
            name='inventor_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='patentapplication',
            name='startup_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='advantages',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='detailed_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.district'),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='drawbacks_overcome',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='enclosures',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='field_of_invention',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='inventor_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='inventor_signatures',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='novel_features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='objectives',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='patent_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.state'),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='state_of_art',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='test_status',
            field=models.TextField(),
        ),
    ]
