# Generated by Django 4.2.23 on 2025-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0013_remove_patentapplication_applicant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentapplication',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='company_classification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='dpiit_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='inventor_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='inventor_details',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='startup_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='uam_certificate',
            field=models.FileField(upload_to='certificates/'),
        ),
    ]
