# Generated by Django 4.2.23 on 2025-09-14 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0014_alter_patentapplication_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patentapplication',
            name='field_of_invention',
        ),
        migrations.RemoveField(
            model_name='patentapplication',
            name='inventor_signatures',
        ),
        migrations.AddField(
            model_name='patentapplication',
            name='enclosed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patentapplication',
            name='enclosed_file',
            field=models.FileField(blank=True, null=True, upload_to='enclosed_files/'),
        ),
        migrations.AddField(
            model_name='patentapplication',
            name='invention_category',
            field=models.CharField(choices=[('Process', 'Process'), ('Product', 'Product')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='patentapplication',
            name='patent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patentapplication',
            name='patent_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patentapplication',
            name='stage_of_development',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='contact_number',
            field=models.CharField(help_text='Must be exactly 10 digits.', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='detailed_description',
            field=models.FileField(upload_to='detailed_descriptions/'),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='enclosures',
            field=models.FileField(upload_to='enclosures/'),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='inventor_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='patent_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='test_status',
            field=models.CharField(max_length=50),
        ),
    ]
