# Generated by Django 4.2.23 on 2025-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0015_remove_patentapplication_field_of_invention_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patentapplication',
            old_name='detailed_description',
            new_name='detailed_description_file',
        ),
        migrations.RemoveField(
            model_name='patentapplication',
            name='enclosures',
        ),
        migrations.AddField(
            model_name='patentapplication',
            name='reprints_file',
            field=models.FileField(default=1, upload_to='reprints/'),
            preserve_default=False,
        ),
    ]
