# Generated by Django 4.2.23 on 2025-09-14 17:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_repo', '0002_alter_district_name_alter_district_state_and_more'),
        ('techforms', '0016_rename_detailed_description_patentapplication_detailed_description_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priorartsearch',
            old_name='applicant_name',
            new_name='startup_name',
        ),
        migrations.AlterField(
            model_name='priorartsearch',
            name='contact_number',
            field=models.CharField(help_text='Must be exactly 10 digits.', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='priorartsearch',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.district'),
        ),
        migrations.AlterField(
            model_name='priorartsearch',
            name='inventor_details',
            field=models.TextField(blank=True, default='{}', help_text='JSON string storing inventor details: {inventor_1: {name, designation, dob, qualification, mobile, email}, ...}'),
        ),
        migrations.AlterField(
            model_name='priorartsearch',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.state'),
        ),
    ]
