# Generated by Django 4.2.23 on 2025-09-18 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0017_rename_applicant_name_priorartsearch_startup_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(help_text='Must be exactly 10 digits.', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('organization_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('patent_title', models.CharField(max_length=255)),
                ('area_of_interest', models.CharField(max_length=100)),
                ('collaboration_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('mode_of_contact', models.CharField(max_length=100)),
                ('reason', models.TextField(max_length=5000)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('agree_to_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
