# Generated by Django 4.2.23 on 2025-09-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0018_expressinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarkapplication',
            name='duration_of_use',
            field=models.TextField(default='NA', max_length=5000),
        ),
        migrations.AddField(
            model_name='trademarkapplication',
            name='proof_of_use',
            field=models.FileField(blank=True, null=True, upload_to='trademark_proofs/'),
        ),
        migrations.AddField(
            model_name='trademarkapplication',
            name='supporting_proof',
            field=models.FileField(blank=True, null=True, upload_to='trademark_supporting_proofs/'),
        ),
        migrations.AddField(
            model_name='trademarkapplication',
            name='trademark_status',
            field=models.TextField(default='NA', max_length=5000),
        ),
    ]
