# Generated by Django 4.2.23 on 2025-09-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0019_trademarkapplication_duration_of_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressinterest',
            name='collaboration_type',
        ),
        migrations.RemoveField(
            model_name='expressinterest',
            name='mode_of_contact',
        ),
        migrations.AlterField(
            model_name='expressinterest',
            name='area_of_interest',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expressinterest',
            name='reason',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
