# Generated by Django 4.2.23 on 2025-09-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_repo', '0003_tech_director_inventor'),
        ('techforms', '0020_remove_expressinterest_collaboration_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='innovationvoucherapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Innovation Voucher Application', 'verbose_name_plural': 'Innovation Voucher Applications'},
        ),
        migrations.RenameField(
            model_name='trademarkapplication',
            old_name='applicant_name',
            new_name='startup_name',
        ),
        migrations.RemoveField(
            model_name='innovationvoucherapplication',
            name='director_details',
        ),
        migrations.RemoveField(
            model_name='patentapplication',
            name='inventor_details',
        ),
        migrations.RemoveField(
            model_name='priorartsearch',
            name='inventor_details',
        ),
        migrations.RemoveField(
            model_name='trademarkapplication',
            name='inventor_details',
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='commercialization_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='commercialization_ivp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='fabrication_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='fabrication_ivp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='ipr_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='ipr_ivp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='other1_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='other1_ivp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='other2_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='other2_ivp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='outsourcing_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='outsourcing_ivp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='raw_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='raw_ivp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='testing_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='testing_ivp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='innovationvoucherapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='innovationvoucherapplication',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='innovationvoucherapplication',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='innovationvoucherapplication',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.district'),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.state'),
        ),
        migrations.AlterField(
            model_name='patentapplication',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priorartsearch',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trademarkapplication',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
