# Generated by Django 6.0 on 2025-12-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_repo', '0003_tech_director_inventor'),
        ('tech_website', '0007_alter_technology_description'),
        ('techforms', '0021_alter_innovationvoucherapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pdf_write', models.FileField(blank=True, null=True, upload_to='patents/pdf/')),
                ('word_write', models.FileField(blank=True, null=True, upload_to='patents/word/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('unique_id', models.CharField(editable=False, max_length=6, null=True, unique=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.district')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_website.sector')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech_repo.state')),
            ],
        ),
    ]
