# Generated by Django 4.2.23 on 2025-12-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techforms', '0022_patent'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
