# Generated by Django 5.2.5 on 2025-09-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
