# Generated by Django 4.2.23 on 2025-09-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_website', '0003_alter_sector_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
