# Generated by Django 4.2.23 on 2025-09-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_website', '0005_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='unique_id',
            field=models.CharField(editable=False, max_length=6, null=True, unique=True),
        ),
    ]
