# Generated by Django 6.0 on 2025-12-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_website', '0006_technology_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
