# Generated by Django 4.2.23 on 2025-12-08 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tech_website', '0007_alter_technology_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
